# Generated by Django 5.2.5 on 2025-08-13 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RetainedSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=16)),
                ('player_name', models.CharField(max_length=128)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retentions', to='trades.team')),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_team_abbr', models.CharField(max_length=5)),
                ('year', models.IntegerField()),
                ('rnd', models.IntegerField()),
                ('overall', models.IntegerField(blank=True, null=True)),
                ('owning_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks_owned', to='trades.team')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhl_id', models.CharField(db_index=True, max_length=32)),
                ('full_name', models.CharField(max_length=128)),
                ('position', models.CharField(blank=True, default='', max_length=8)),
                ('dob', models.CharField(blank=True, default='', max_length=32)),
                ('height', models.CharField(blank=True, default='', max_length=16)),
                ('weight', models.CharField(blank=True, default='', max_length=16)),
                ('shoots', models.CharField(blank=True, default='', max_length=8)),
                ('nhl_rights', models.CharField(blank=True, default='', max_length=64)),
                ('nhl_rights_abbrv', models.CharField(blank=True, default='', max_length=5)),
                ('contract_type', models.CharField(blank=True, default='', max_length=32)),
                ('contract_length', models.IntegerField(blank=True, null=True)),
                ('years_remaining', models.IntegerField(blank=True, null=True)),
                ('last_season', models.CharField(blank=True, default='', max_length=16)),
                ('contract_value', models.BigIntegerField(blank=True, null=True)),
                ('cap_hit', models.BigIntegerField(blank=True, null=True)),
                ('expiry_status', models.CharField(blank=True, default='', max_length=32)),
                ('clause_details', models.CharField(blank=True, default='', max_length=256)),
                ('waivers_eligible', models.CharField(blank=True, default='', max_length=16)),
                ('exclude_50contract', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='trades.team')),
            ],
        ),
    ]
