# Generated by Django 5.2.5 on 2025-08-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='nhl_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
