# Generated by Django 5.2.5 on 2025-08-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_contract_nhl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpick',
            name='original_team_abbr',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
